DELETE http://localhost:3003/api/blogs/679411fe22fe51209b007040
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFub3RoZXIgVXNlciIsImlkIjoiNjc5NDExMmIyMmZlNTEyMDliMDA3MDJmIiwiaWF0IjoxNzM3NzU3MDAxLCJleHAiOjE3Mzc3NjA2MDF9.o7WMUjz_hFp4WL-wJWPPN_Kh4FvYIo-2AatzqOsEcKU